on:
  pull_request:
    types: [opened, synchronize, reopened, ready_for_review]
  push:
    branches:
      - main
      - 'dev*'

env:
  NODE_ENV: ci

permissions:
  contents: read

jobs:
  CI:
    timeout-minutes: 60
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.10"]
        poetry-version: ["1.8.2"]

    steps:
        uses: actions/checkout@v3
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
        uses: abatilo/actions-poetry@v2
        with:
          poetry-version: ${{ matrix.poetry-version }}
        run: poetry run pytest

      - name: Lint pylint
        run: poetry run pylint **/*.py

      - name: Lint flake8
        run: poetry run flake8
