on:
  pull_request:
    types: [opened, synchronize, reopened, ready_for_review]
  push:
    branches:
      - main
      - 'dev*'

env:
  NODE_ENV: ci

permissions:
  contents: read

jobs:
  CI:
    timeout-minutes: 120
    runs-on: ubuntu-latest

    strategy:
      matrix:
        python-version: ["3.10"]

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install poetry
          poetry install

      - name: Test Unit
        run: poetry run pytest

      - name: Lint pylint
        run: poetry run pylint **/*.py

      - name: Lint flake8
        run: poetry run flake8
